Tarsnap/tarsnap-gui

src/taskmanager.cpp

The regex would fail with 'humanize-numbers' set in my config file. Just add '--no-humanize-numbers' to avoid this in the two places that I found would correct the problem.

Issues when 'humanize-numbers' set in config

---

INSTALL

The `export` is spurious and the command as-is will not work. `QT_SELECT` is only required to run `qmake`, so this changes it so it's only done for the qmake command.

Fix INSTALL instructions for Debian-based distros

---

src/widgets/mainwindow.cpp

On Ubuntu 14.04 with the main window as narrow as possible, the "----" lines
overflowed so that there was an entire row of "-------" followed by three
"---" on the next line.

Console: use fewer dashes

---

forms/setupdialog.ui

Apparently a normal QLabel doesn't "reserve" space for letters which have
parts below the baseline (i.e. "gjpqy") ?!  This commit sets a minimum
vertical space for the setup titles to avoid the bottom portion of "p" and "g"
being cut off.

Setup: add minimum vsize to title to avoid cutoff

---

forms/setupdialog.ui

I think it might be nice to imitate the way the Tarsnap website handles `<aside>` comments:
http://www.tarsnap.com/
This re-adds the left margins that were removed in a61e2e5, and adds a `border-left` to add more visual emphasis that this is a different type of comment than the plain text.

Setup: mimic website CSS for "aside" comments

---

forms/setupdialog.ui

The "faded" text color turned out to be darker than the default text on Ubuntu
14.04, so I removed the color change.  I didn't realize that different systems
have different default text colors.
Details are as follows.  On my main system (icewm), adding:
qDebug() <<
_ui->welcomePageInfoLabel->palette().color(
QPalette::WindowText);
shows that it's black:
src/widgets/setupdialog.cpp(111): QColor(ARGB 1, 0, 0, 0)
However, on Ubuntu 14.04 with the default UI, I see:
src/widgets/setupdialog.cpp(111): QColor(ARGB 1, 0.298039, 0.298039, 0.298039)

Setup: remove text color from "aside" comments

---

src/widgets/mainwindow.cpp

The "background" variable wasn't being used, and it doesn't seem to be
necessary to check for it in the "if" statments (lower in the function).

Remove compiler warning about an unused variable

---

src/taskmanager.cpp

The recent commit b6dfb04b418499e58ce5b56527566037c15c289f added a `.trimmed()` to the command-line output, so the previous regex failed to find the version string.

Allow optional whitespace in Tarsnap version regex

---

src/taskmanager.cpp

This reverts commit f8d66750927d2fcd4f21da0588aa08873bdcdadd.
In English, we normally have a space after a bunch of... dots.

Revert "Remove extraneous space after suspension dots."

---

forms/joblistwidgetitem.ui
src/widgets/joblistwidgetitem.cpp

This increases consistency in the app:
- in the Backup list, the right-most is "remove this file/dir"
- in the Archive list, the right-most is delete
- right-clicking in the Jobs list shows Backup, Info, Restore, Delete.
Moving the Backup icon to the left position (in the right-most block of icons) and adding a Delete icon to the right makes the icons match the right-click menu.

JobListWidgetItem: add delete to UI

---

forms/setupdialog.ui

Without this, the "Create new keyfile" sub-page is smaller than
the "Use existing keyfile" sub-page, so changing between them
makes whole vertically centered page jump around.

setup: same vertical height on the "Register with server" page

---

src/tarsnaptask.cpp
src/utils.cpp
src/utils.h

The previous commands would fail if a directory contained a space (for example, with the default ".../Tarsnap Backup Inc./..."). QProcess automatically escapes spaces in arguments before it runs
a command, but unbelievably there is no way to access the "escaped" arguments.  (QProcess.arguments() returns the un-escaped strings)
Adding double-quotes around each argument seems like a safer solution than trying to escape spaces.  I admit it that it looks weird to see things like
/usr/bin/tarsnap "--version"
but I think that's an acceptable sacrifice (although clearly not ideal!).
NOTE: the actual command that QProcess runs is *not* changed by this commit.  This commit only changes what is displayed on the command-line and console log.

Display copy&pasteable commands

---

src/widgets/archivewidget.h

We haven't used the term "custom" to describe any of the other subclassed Qt objects; I think that's implied.

ArchiveWidget: remove "custom" from doxygen

---

forms/mainwindow.ui

Without a minimum height on mainTabWidget, Qt uses the sizeHint as the minimum
sizes, and we end up with a main display that can't be shorter than 603 pixels.
For reference, the default Ubuntu 14.04 GUI (on a 640x480 screen) allows up to
456 pixels high for a maximized window, or 428 for a non-maximized one.

Set a minimum height (for small displays)

---

Tarsnap.pro

We use QLineEdit->setClearButtonEnabled(), which was introduced in 5.2:
http://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop

Check for Qt 5.2 or higher

---

src/widgets/mainwindow.cpp

This might be an issue of window manager and/or Qt version, but the previous
version could have the logo (partly) hiding behind the "Help" tab.  This
change:
- compares a "remaining width" against the width in of the actual png files,
so it's easier to see what's happening.
- condenses the "fudge factor" to a single +8 that's applied to this value.
If we discover more problems with this spacing, we'll have a single place
to investigate.

Avoid MainWindow logo overlapping the "Help" tab.

---

src/widgets/restoredialog.cpp

This only applies when restoring an entire archive.

RestoreDialog: don't display if file list if not available

---

src/coreapplication.cpp
src/widgets/mainwindow.cpp
src/widgets/mainwindow.h

I was quite confused about the original name; I think that appending "Dialog"
will help a lot.
I also revised the doxygen comment: I think it's important to specify that this
function is responsible for actually quitting the app.  Longer-term, I might
propose some kind of refactoring to the app quitting logic to avoid having the
->quit() inside a "Dialog" function, but right now, I think the priority should
be clarifying what's currently happening.

Rename MainWindow::displayStopTasks to displayStopTasksDialog

---

forms/mainwindow.ui
src/widgets/mainwindow.cpp
src/widgets/mainwindow.h

Without this patch, a user could click on "About Tarsnap" multiple times,
generating a window each time.

Only display one "About" window at once

---

src/tarsnapaccount.cpp

Fixes https://github.com/Tarsnap/tarsnap-gui/issues/179

tarsnapaccount.cpp: include QHeaderView for Qt 5.11.0 compatibility

---

INSTALL

Step 2 is now unnecessary. If you run that command, you get the following message from `brew`:
> Error: homebrew/gui was deprecated. This tap is now empty as all its formulae were migrated.
Everyone can now `brew install tarsnap-gui` directly.

The homebrew/gui tap is empty and deprecated

---

src/persistentmodel/job.cpp

There was a syntax error in the `update jobs` SQL statement, preventing users from modifying values for existing jobs. (E.g. changing a job's update schedule from Disabled to Daily.)

Fix updating existing jobs
